private ["_long"];
_long = ;
private ["_cariHealt","_target"];_target = _this select 0;
_target allowDamage false;
if (vehicle _target == _target) then {_target setDamage 0;};
_target setVariable ["hit_legs",0,true];
_target setVariable ["hit_hands",0,true];
_target setVariable ["messing",[0,0],true];
_target setVariable ["NORRN_unconscious",false,true];
_target setVariable ["startcombattimer",0,true];
_target setVariable ["combattimeout",0,true];
_target setVariable ["unconsciousTime",0,true];
_target setVariable ["USEC_BloodQty",11789,true];
_target setVariable ["USEC_infected",false,true];
_target setVariable ["USEC_injured",false,true];
_target setVariable ["USEC_inPain",false,true];
_target setVariable ["USEC_isCardiac",false,true];
_target setVariable ["USEC_lowBlood",false,true];
_target setVariable ["medForceUpdate",true,true];
_target setVariable ["body",false,true];
_target setVariable ["head_hit",false,true];
_target setVariable ["legs",false,true];
_target setVariable ["hands",false,true];_cariHealt = format ["
	if (name player == '%1') then {
		if (%2) then {
			dayz_temperatur = 36;
			dayz_hunger = 0;
			dayz_sourceBleeding = objNull;
			dayz_thirst = 0;
			r_action = false;
			r_action_unload = false;
			r_doLoop = false;
			r_drag_sqf = false;
			r_fracture_legs = false;
			r_fracture_arms = false;
			r_handlercount = 0;
			r_interrupt = false;
			r_player_cardiac = false;
			r_player_handler = false;
			r_player_handler1 = false;
			r_player_infected = false;
			r_player_injured = false;
			r_player_inpain = false;
			r_player_loaded = false;
			r_player_lowblood = false;
			r_player_timeout = 0;
			r_player_unconscious = false;
			r_self = false;
			if (r_player_blood < 7000) then {r_player_blood = 11988;};
		};
		'dynamicBlur' ppEffectAdjust [0]; 
		'dynamicBlur' ppEffectCommit 5;
		disableUserInput false;
		player setHit ['body',0];
		player setHit ['hands',0];
		player setHit ['legs',0];
		0 fadeSound 1;
		resetCamShake;
	};
",name _target,cariDayz];
[_cariHealt] call cariRE;systemChat format ["%1 was healed",name _target];