private ["_rExec"];

_rExec = compile ("
waitUntil {!isNil ""dayz_animalCheck""};

if (p2SpT) then { _time = diag_tickTime; diag_log format ['menu showText.sqf started, Time: %1',_time]; };



p2menu_showText = {
	disableSerialization;
	_zombz4 = _this select 0; _zombzText = 114;

	lbClear _zombzText;
	lbsetcolor[114,0,[1,1,1,0.8]];
	switch (_zombz4) do
	{
		case ""news"":
		{
			call compile PV_news;
		};
		case ""blank"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Need more information? Visit our website""];
			lbAdd [_zombzText, "" WWW.ZOMBZ.NET""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]]
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" or join our Teamspeak 3 Server""];
			lbAdd [_zombzText, "" TS3.zombz.net:9172""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]]
		};
		case ""rules"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Player Rules:""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""These apply to all players, donators and staff on""];
			lbAdd [_zombzText, ""our servers.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" 1) No Glitching/Exploiting""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 2) No Duping of any items in game""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 3) No Killing in debug""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 4) No racial/hateful language""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 5) No Kamikaze (unless shot at)""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 6) No Ghosting (we can track this if reported)""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 7) No Combat Logging""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 8) No Excessive Advertising""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 9) No killing from inside donator bases""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 10) Respect staff, they work to keep the servers safe""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Our staff members have access to lots of forms of information""];
			lbAdd [_zombzText, "" including log in/log out times. What servers you logged in to""];
			lbAdd [_zombzText, "" wether you crashed a helicopter recently. They will always use""];
			lbAdd [_zombzText, "" as much evidence as they can before coming to a decision,""];
			lbAdd [_zombzText, "" regarding a breach of the rules""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Need more information? Visit our website""];
			lbAdd [_zombzText, "" WWW.ZOMBZ.NET""];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, ""   ""];
		};
		case ""serverinfo"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Server Information""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" You are playing on ZombZ Dayz Mod. This""];
			lbAdd [_zombzText, "" server runs dayz 1.8.1 (See the ""];
			lbAdd [_zombzText, "" About Dayz Mod section) ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" These Servers are run on a dedicated server""];
			lbAdd [_zombzText, "" with 1gb internet, really powerful componants""];
			lbAdd [_zombzText, "" including an SSD to help improve performance.""];
			lbAdd [_zombzText, "" ""];
	
			lbAdd [_zombzText, "" Why play this server?""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" This server is constantly updated by proffesional""];
			lbAdd [_zombzText, "" coders. They introduce new and unseen features""];
			lbAdd [_zombzText, "" using methods that arnt normally known about.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" We have a huge staff team, who work behind the""];
			lbAdd [_zombzText, "" scenes, monitoring chat, kill feeds and many""];
			lbAdd [_zombzText, "" other detection methods.""];
			lbAdd [_zombzText, "" We do not run server side anti hacks. They""];
			lbAdd [_zombzText, "" are literally hack menus that allow staff to""];
			lbAdd [_zombzText, "" to seriously abuse powers.""];
			lbAdd [_zombzText, "" Our staff members can support in removing unconcious""];
			lbAdd [_zombzText, "" status, and teleporting a player to completly""];
			lbAdd [_zombzText, "" random location (they can not pick the location)""];
			lbAdd [_zombzText, "" This requires the player to be logged out from""];
			lbAdd [_zombzText, "" the server. Therefore stopping any possible abuse""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Our servers are protected by SKYNET, an automated""];
			lbAdd [_zombzText, "" system written by out staff. That monitors""];
			lbAdd [_zombzText, "" everything a player gets up to. It is capable""];
			lbAdd [_zombzText, "" of learning when player moves are safe. But also""];
			lbAdd [_zombzText, "" when they are not.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Here at zombz we pride ourselves on our servers.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Arma 2 engine is very poor at having huge amounts""];
			lbAdd [_zombzText, "" of players at one time. The more players with bad""];
			lbAdd [_zombzText, "" connections. The more desync spikes servers get.""];
			lbAdd [_zombzText, "" We combat this by having certain bandwidth""];
			lbAdd [_zombzText, "" restrictions in place, as well as a max ping.""];
			lbAdd [_zombzText, "" ""];
		};
		case ""serverexplain"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" About Dayz Mod""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" Dayz is a survival zombie horror mod.""];
			lbAdd [_zombzText, "" The goal of the game is to scavenge for ""];
			lbAdd [_zombzText, "" supplys and weapons to help you survive""];
			lbAdd [_zombzText, "" the horrors of this post apocolyptic""];
			lbAdd [_zombzText, "" world.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" It is upto you to decide how you want to play.""];
			lbAdd [_zombzText, "" Scavange and search for supplys in buildings""];
			lbAdd [_zombzText, "" Raid hospitals for much needed medical supplys""];
			lbAdd [_zombzText, "" Move inland and discover carepackage drops,""];
			lbAdd [_zombzText, "" Helicopter crashes, Supply caches.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Become a hero. Help players by healing them""];
			lbAdd [_zombzText, "" shooting bandits, or completing bandit AI missions""];
			lbAdd [_zombzText, "" to improve your humanity.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Be a survivor. Move off into the wilderness. Only""];
			lbAdd [_zombzText, "" venturing into danger when you need to, surviving""];
			lbAdd [_zombzText, "" by hunting down animals, cooking their meat on""];
			lbAdd [_zombzText, "" open fires. Hunting down base building supplies""];
			lbAdd [_zombzText, "" when you think your safe, and using them to build""];
			lbAdd [_zombzText, "" your home.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Or be the person everyone hates. The Bandit. Hunt""];
			lbAdd [_zombzText, "" people down, make them drop their gear. Or simply just""];
			lbAdd [_zombzText, "" shoot them in the face for their beans""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Whatever you decide to do, Dayz has a vast variaty""];
			lbAdd [_zombzText, "" of choice with its extra weapons and vehicles and ""];
			lbAdd [_zombzText, "" ZombZ's custom code. ""];
			lbAdd [_zombzText, "" You will never find more action on any server!""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Player Testitmonials""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" [TPB] Logan: Dont know much about epoch but so""];
			lbsetcolor[114, (lbsize 114)-1,[0,1,0,0.8]];
			lbAdd [_zombzText, "" far im really loving it the staff are so helpful""];
			lbsetcolor[114, (lbsize 114)-1,[0,1,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Bob: Loving it so far, great work zombz team, bringing your""];
			lbsetcolor[114, (lbsize 114)-1,[0,1,0,0.8]];
			lbAdd [_zombzText, "" specialist take to Epoch""];
			lbsetcolor[114, (lbsize 114)-1,[0,1,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Handyandy: Seriously? I can move my gold between maps and servers? ""];
			lbsetcolor[114, (lbsize 114)-1,[0,1,0,0.8]];
			lbAdd [_zombzText, "" wow just wow, these guys are awesome sauce""];
			lbsetcolor[114, (lbsize 114)-1,[0,1,0,0.8]];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, ""   ""];

		};
		
		case ""staff"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" About our staff""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, """"];
			lbAdd [_zombzText, "" Our staff members volunteer their time to""];
			lbAdd [_zombzText, "" provide our players with a safe, fun enviroment""];
			lbAdd [_zombzText, "" in which our player base can enjoy their time.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Unfortunatly alot of people dont realise this. So""];
			lbAdd [_zombzText, "" we ask that you show our staff members the utmost""];
			lbAdd [_zombzText, "" respect""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" If you have an issue with a specific staff member""];
			lbAdd [_zombzText, "" feel free to post on the forums, and your issue""];
			lbAdd [_zombzText, "" will be reveiwed.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" We pride ourselves on not having admin abuse on our""];
			lbAdd [_zombzText, "" servers. All of our staff have to undergo a trial""];
			lbAdd [_zombzText, "" period. During which they are taught how to track""];
			lbAdd [_zombzText, "" different issues through our website. So that""];
			lbAdd [_zombzText, "" they are able to deal with the different dayly""];
			lbAdd [_zombzText, "" issues that may arrise.""];
			lbAdd [_zombzText, "" At the end of their trial period they are reviewed""];
			lbAdd [_zombzText, "" by our management staff. Who then decide wether""];
			lbAdd [_zombzText, "" the person knows enough, (aswell as using evidence""];
			lbAdd [_zombzText, "" when it comes to banning).""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" We would like to take the time to thank our""];
			lbAdd [_zombzText, ""GREAT team of staff, for all the hard work they""];
			lbAdd [_zombzText, "" put in. So Thank You All!""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Want to join the team?""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, """"];
			lbAdd [_zombzText, "" Fill out an application on our website or""];
			lbAdd [_zombzText, "" contact management in teamspeak 3.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Upon being accepted to our staff team, you will""];
			lbAdd [_zombzText, "" be given the moderator rank. Our management will""];
			lbAdd [_zombzText, "" then be responsible for teaching you how to use""];
			lbAdd [_zombzText, "" our systems, and monitoring your progress""];
			lbAdd [_zombzText, "" To prevent the many POWER CRAZZZZY people out there""];
			lbAdd [_zombzText, "" you will not be able to perma ban until you""];
			lbAdd [_zombzText, "" are ready to be made an admin.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];

		};
		case ""feature"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Server Feature List""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" Loot Tables""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Over 800 weapons unlocked""];
			lbAdd [_zombzText, "" - HEAVILY modified loot table""];
			lbAdd [_zombzText, "" - Weapon spawns change from north to south  ""];
			lbAdd [_zombzText, "" - Ultra-rare weapon spawns""];
			lbAdd [_zombzText, "" - Helicopter crash site loot is insane""];
			lbAdd [_zombzText, "" - Industrial ural wrecks (yellow smoke)""];
			lbAdd [_zombzText, "" - Medical humvee wrecks (red smoke)""];
			lbAdd [_zombzText, "" - Military supply drop packages (green smoke)  ""];
			lbAdd [_zombzText, "" Debug Monitor""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Press F5 to toggle it on and off.""];
			lbAdd [_zombzText, "" A.I Missions""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Armed AI Bandits spawn protecting an area  ""];
			lbAdd [_zombzText, "" - You may loot their bodies for guns, or""];
			lbAdd [_zombzText, "" - loot the crates that they gaurd.""];
			lbAdd [_zombzText, "" - Look for red or green areas on the map.  ""];
			lbAdd [_zombzText, "" Custom Map Areas""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - All of these locations have a lot of loot""];
			lbAdd [_zombzText, "" - and powerful vehicle spawns.""];
			lbAdd [_zombzText, "" - Check the map to see the outpost locations.  ""];
			lbAdd [_zombzText, "" - We have also modified existing areas.""];
			lbAdd [_zombzText, "" - PS: not all locations are marked. ""];
			lbAdd [_zombzText, "" Molotovs""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" -  Any empty whisky bottle is a molotov""];
			lbAdd [_zombzText, "" -  please handle with caution.""];
			lbAdd [_zombzText, "" Vehicle Spawns""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - We have added over a thousand hidden""];
			lbAdd [_zombzText, ""   vehicle spawn points, many of which""];
			lbAdd [_zombzText, ""   are powerful military vehicles.""];
			lbAdd [_zombzText, "" Strip Vehicle Parts""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Use a toolbox to remove vehilcle parts""];
			lbAdd [_zombzText, "" Strip clothes from body""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Scroll on a body to take their clothes""];
			lbAdd [_zombzText, "" Random Starter Loadouts and Skins""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - You will spawn with a random loadout""];
			lbAdd [_zombzText, ""    and skin every time.""];
			lbAdd [_zombzText, "" Halo Jump Spawn with Music""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Spawn parachuting to randomised music""];
			lbAdd [_zombzText, "" Added Vehicle Weapons""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - We put cannons on some vehicles.""];
			lbAdd [_zombzText, "" Auto-Refuel""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Park next to a pump or fuel tank""];
			lbAdd [_zombzText, ""    then get out and scroll to refuel.""];
			lbAdd [_zombzText, "" Death Messages""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Customised Death Messages (top left)""];
			lbAdd [_zombzText, ""   Keep in mind that it registers the last person to""];
			lbAdd [_zombzText, ""   hit you, so even after 10k travel, they get the kill""];
			lbAdd [_zombzText, "" Craftable Vehicles""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Create vehicles and upgrade them using your toolbox""];
			lbAdd [_zombzText, ""   and other vehicle parts (see Recipe list on menu)""];
			lbAdd [_zombzText, "" F1 Help Menu""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Your looking at it! Another ZombZ first""];
			lbAdd [_zombzText, "" Removed OP vehicle weapons""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - We have removed some of the super OP missiles""];
			lbAdd [_zombzText, ""   on some vehicles to allow them to be used in the""];
			lbAdd [_zombzText, ""   server.""];
			lbAdd [_zombzText, "" More ways to farm humanity""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - AI missions""];
			lbAdd [_zombzText, "" - Killing Bandits""];
			lbAdd [_zombzText, "" - Giving Blood""];
			lbAdd [_zombzText, "" Sexy Map Markers""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Upgraded sexy map markers for the custom areas""];
			lbAdd [_zombzText, "" Randomised Teleport/Heal unconcious""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Done via our website, allows our staff to fix you up, ""];
			lbAdd [_zombzText, ""   and also teleport you out the ocean, to a completly""];
			lbAdd [_zombzText, ""   random location. Player must be logged out.""];
			lbAdd [_zombzText, "" Banking System""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - This allows you to store gold safely and transfer""];
			lbAdd [_zombzText, "" 	it to our other servers.""];
			lbAdd [_zombzText, "" Base Building Carepackages""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Look for the purple smoke!""];
			lbAdd [_zombzText, "" Airfields redone""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" Mass Airplanes at every airfield, Respawn on Restart""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" SkyNet Security""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Our own server security extension""];
			lbAdd [_zombzText, ""    that uses A.I. to learn and ban""];
			lbAdd [_zombzText, ""    cheaters without requiring an update""];
			lbAdd [_zombzText, ""    it also reports all suspect behaviour""];
			lbAdd [_zombzText, ""    to a moderation team that is online""];
			lbAdd [_zombzText, ""    nearly 24/7. You wont find this kind of""];
			lbAdd [_zombzText, ""    security anywhere else in DayZ.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
		};
		case ""feature1"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Deployable Vehicles""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, ""Using a toolbox you can create,""];
			lbAdd [_zombzText, ""upgrade, and strip vehicles into parts.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""To get started, use your starting toolbox""];
			lbAdd [_zombzText, ""and build yourself a bicycle!""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""You may only upgrade deployed vehicles.""];
			lbAdd [_zombzText, ""To upgrade a vehicle, just scroll on it.""];
			lbAdd [_zombzText, ""It will tell you the parts you require.""];
			lbAdd [_zombzText, ""You do need a toolbox to see your options.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Any type of large machine gun can be used""];
			lbAdd [_zombzText, ""when upgrading to an armed vehicle.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""List of upgrades you can perform:""];
			lbAdd [_zombzText, ""-Land Vehicles-""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  Bike --> Motorbike --> ???? --> ????""];
			lbAdd [_zombzText, ""  Bike --> ATV --> ???? --> ????""];
			lbAdd [_zombzText, ""  Bike --> Tractor --> ???? --> ????""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""-Air Vehicles-""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 2 Man heli --> LittleBird (Unarmed)""];
			lbAdd [_zombzText, "" LittleBird (Unarmed) --> ????""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Please note, these vehicles do save""];
			lbAdd [_zombzText, ""after restarts. ""];
			lbAdd [_zombzText, ""Yeh thats right, your gonna have to build to see""];
			lbAdd [_zombzText, """"];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Helicopters that contain guns, also require a heavy machine gun""];
			lbAdd [_zombzText, "" before you can upgrade them.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" * Upgrade options can be difficult to get at,""];
			lbAdd [_zombzText, ""   try and prone under the rear of the heli.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
		};
		case ""feature2"":
		{
			lbAdd [_zombzText, "" Some other detailed feature can go here ""];
		};

		case ""base"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Bases""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Our bases are purchasable through the website. They are a great""];
			lbAdd [_zombzText, "" way to support our servers while bringing alot of fun back into""];
			lbAdd [_zombzText, ""  the game. Have you ever got tired of having your tent raided? ""];
			lbAdd [_zombzText, "" want more fun when  you join the server? Check out the features ""];
			lbAdd [_zombzText, "" listed below. Keep in mind, that we reset server vehicles once a""];
			lbAdd [_zombzText, "" week, to stop mass hording of vehicles. Allowing our non paying ""];
			lbAdd [_zombzText, "" players more vehiclesmeans more fun for you guys when it comes to ""];
			lbAdd [_zombzText, "" air battles. (vehicles purchased with the base will always spawn""]; 
			lbAdd [_zombzText, "" at your base every restart)""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Donator Base Features:""];
			lbAdd [_zombzText, ""        ""];
			lbAdd [_zombzText, "" Respawn at base""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Every time you die, you have the option to spawn at your base""];
			lbAdd [_zombzText, "" Vehicles auto-respawn at base ""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Every restart, vehicles purchased with the base will respawn.""];
			lbAdd [_zombzText, "" Large gear storage boxes""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Capable of storing 1000s of your most valuable items""];
			lbAdd [_zombzText, "" Dual Dome protection:""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - 50m teleport dome""];
		 	lbAdd [_zombzText, ""        This moves unauthorised players away from the base on first""];
			lbAdd [_zombzText, ""        entry attempt, breaks legs on second, the third attempt will""];
			lbAdd [_zombzText, ""        kill the player.""];
			lbAdd [_zombzText, ""  - 15m god mode dome""];
			lbAdd [_zombzText, ""        This prevents zombies or players from harming you while ""];
			lbAdd [_zombzText, ""        inside your base""];
			lbAdd [_zombzText, ""        ""];
			lbAdd [_zombzText, "" Remote locations:""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Bases are in remote locations, most located in the far north or far ""];
			lbAdd [_zombzText, ""    west fairly close to the edge of the maps. This makes the northern  ""];
			lbAdd [_zombzText, ""    and western areas of the map alot more interesting in terms of ""];
			lbAdd [_zombzText, ""    who you might run into. With the various airfields (some custom ""];
			lbAdd [_zombzText, ""    built) and  custom built outposts, these areas of the map will ""];
			lbAdd [_zombzText, ""    offer a very interesting experience for our players.  ""];
			lbAdd [_zombzText, "" Improves player count stability""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - By selling bases it gives squads more incentive to play our servers.""];
			lbAdd [_zombzText, ""    This means more players online, more exciting encounters and deadly""];
			lbAdd [_zombzText, ""    battles for bragging rights. If you love action, you have to love our ""];
			lbAdd [_zombzText, ""  	 servers""];
			lbAdd [_zombzText, "" Great for Streamers or Youtubers""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Having a base with safe storage and vehicles every respawn allows""];
			lbAdd [_zombzText, ""    you to get into action quicker. Lets face it, do people want to watch""];
			lbAdd [_zombzText, ""    Dayz overwatch the running simulator? or do they want to watch crazy""];
			lbAdd [_zombzText, ""    eventful, totally unpredictable, action event after event?""];
			lbAdd [_zombzText, "" Donator Login""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - You can upgrade and make changes to your base via our custom web""];
			lbAdd [_zombzText, ""     login panel for donators only. This will keep track of everyone""];
			lbAdd [_zombzText, ""     in your base and show their stats. So you can compete against ""];
			lbAdd [_zombzText, "" 	  each other for the most kills,laugh at the guy with most deaths.""];
			lbAdd [_zombzText, "" Support System""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - We have staff checking our online donator ticket system, at least 15""];
			lbAdd [_zombzText, ""    times a day, this means fast support, and dealing with any questions ""];
			lbAdd [_zombzText, "" 	 you might have.""];
			lbAdd [_zombzText, "" Server Specific""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  - Availabilty varies between servers. We offer the ability to choose your ""];
			lbAdd [_zombzText, ""   prefered server. Butdue to the limit on bases we have (we dont want to ""];
			lbAdd [_zombzText, ""   disturb the balance of the server by adding 100s). We may not always be ""];
			lbAdd [_zombzText, ""   able to get you on the server you want. However all servers are hived, ""];
			lbAdd [_zombzText, ""   so you can access you character on any.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""See our Website for more Information!""];
			lbAdd [_zombzText, "" www.ZombZ.net""];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, ""   ""];
		};
		case ""loadout"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Donator Loadouts""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Loadouts work on all servers of that type. So purchase an overwatch ""];
			lbAdd [_zombzText, "" and you can access it on all of our overwatch servers. Loadouts are""];
			lbAdd [_zombzText, "" split into 5 sections, upon purchasing anything higher than a $5""];
			lbAdd [_zombzText, "" loadout, you will have the choice between 10 loadouts everytime""];
			lbAdd [_zombzText, "" you die. Making our loadout system, FAR superior to any other""];
			lbAdd [_zombzText, "" server.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Loadout Classes:""];
			lbAdd [_zombzText, "" Choose from these types on every respawn""];
			lbAdd [_zombzText, ""  Scout - Silent weapons""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  Medic - Cover fire weapons with meds""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  Marksman - Long range rifles""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  Engineer - Vehicle builders with LMGs""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""  Soldier - Heavier weaponry""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Loadout Levels Explained:""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Lets say you decide to go for level 3 (the $30 loadout). Everytime""];
			lbAdd [_zombzText, "" you die, you will be given a mousewheel option, that allows you""];
			lbAdd [_zombzText, "" to select from ALL the level 3 loadouts, aswell as all the level 2""];
			lbAdd [_zombzText, "" loadouts (with extra supplies/mags for the level 2 loadout). ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Engineer Explained:""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];

			lbAdd [_zombzText, ""  Different level engineers spawn with parts to build various vehicles""];
			lbAdd [_zombzText, "" that are currently in our craftable vehicle section. This means when""];
			lbAdd [_zombzText, "" you spawn in, you can quickly throw together a vehicle and move""];
			lbAdd [_zombzText, "" quickly to your teams location.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" The vehicle the engineer class can build is determined entirely by""];
			lbAdd [_zombzText, "" the level of the loadout you purchase. Bear in mind that while the""];
			lbAdd [_zombzText, "" engineers weapons are not super awesome like other classes, the""];
			lbAdd [_zombzText, "" weapon rareness doesincrease per level, usually allowing the engineer""];
			lbAdd [_zombzText, ""  to provide covering fire to keep players pinned down.""];
			lbAdd [_zombzText, ""  ""];
			lbAdd [_zombzText, ""  Vehicles per level:""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""        ""];
			lbAdd [_zombzText, ""    Level 1: Motorbike""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""    Level 2: GyroCopter""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""    Level 3: Littlebird""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""    Level 4: Landrover""]; 
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""    Level 5: UH1H Huey""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, ""    Level 6: 50 cal humvee""];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, "" * Upgrade options can be difficult to get at,""];
			lbAdd [_zombzText, ""     try and prone under the rear of the heli.""];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, ""See our Website for more Information!""];
			lbAdd [_zombzText, "" www.ZombZ.net""];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, ""   ""];
		};
		case ""skin"":
		{
			lbAdd [_zombzText, ""Clan Skins""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Ever have that issue in a team where you are shouting at each other?""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Dude, where are you, is that you?! TELL ME IS THAT YOU!!""];
			lbAdd [_zombzText, "" Ah man im dead, that wasnt you...""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Well you no longer have to worry about that, We have unlocked the""];
			lbAdd [_zombzText, "" LHC skins, and kept them strictly for donators, With a multitude of""];
			lbAdd [_zombzText, "" different colors, ranging from yellow to purple to red and more""];
			lbAdd [_zombzText, "" You no longer need to ask the question, is that you?! you will know""];
			lbAdd [_zombzText, "" instantly.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" By purchasing a clan skin, this does not mean you are locked to that""];
			lbAdd [_zombzText, "" skin, it just means that everytime you die, only your clan will have""];
			lbAdd [_zombzText, "" that skin. You can still throw a ghillie or any other clothing you find""];
			lbAdd [_zombzText, "" on to your character.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Interested? Want to know more? Visit our website.""];
		};
		case ""knownbugs"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Known Bugs and Fixes""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Unconcious but no timer""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Try bandanging, relogging, deploying a bike, or getting into a ""];
			lbAdd [_zombzText, ""   vehicle. If still having problems, contact staff on teamspeak.""];
			lbAdd [_zombzText, "" Stuck in the ocean""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Contact a staff member on teamspeak, they will teleport you to""];
			lbAdd [_zombzText, "" a completly random location, They can not choose where.""];
			lbAdd [_zombzText, "" Sepsis""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - Overwatch devs, added this into the game, but failed to add the""];
			lbAdd [_zombzText, ""   wipes, a simple relog will cure you of sepsis""];
			lbAdd [_zombzText, "" Death Messages""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" - 265 M Hatchet kills, 10k M kills etc. This is the last person""];
			lbAdd [_zombzText, "" 	to hit you before you died, this does NOT mean a hacker. Player hits""];
			lbAdd [_zombzText, "" 	you with a hatchet, you crawl away and bleed out, he gets the kill""];
			lbAdd [_zombzText, ""   from where he hit you. even 10,000 meteres away.""];
			lbAdd [_zombzText, "" More to be updated""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];			

		};
		case ""otherserver"":
		{
			lbAdd [_zombzText, ""Other Servers/Games""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Overwatch""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" - Currently running 4 overwatch servers, These are all hived and ""];
			lbAdd [_zombzText, "" 	allow the player to move between them without losing s ""];
			lbAdd [_zombzText, "" 	position/gear. Overwatch i a dayz mod thathas 1000s of weapons""];
			lbAdd [_zombzText, "" 	and 100s of different vehicle added to it. Giving the player a ""];
			lbAdd [_zombzText, ""  more fun feeling on the servers""];
			lbAdd [_zombzText, "" 90 Minute Restart, starting at 00:00""];
			lbAdd [_zombzText, "" Overwatch #1 208.167.247.35:6666 ""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 90 Minute Restart, starting at 00:00 GMT/EST""];
			lbAdd [_zombzText, "" Overwatch #2 208.167.247.35:5555 ""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 90 Minute Restart, starting at 00:30 GMT/EST""];
			lbAdd [_zombzText, "" Overwatch #3 208.167.247.35:4444 ""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 90 Minute Restart, starting at 01:00 GMT/EST""];
			lbAdd [_zombzText, "" Overwatch #4 208.167.247.36:3333 ""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 180 Minute Restart, starting at 00:00 GMT/EST""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Epoch""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" - We Currently run 1 Epoch Panthera server, with the aim to bring ""];
			lbAdd [_zombzText, "" 	out more. Epoch is a type of mod for dayz, that allows players to ""];
			lbAdd [_zombzText, "" 	trade and sell items for gold, build bases, and pretty much do""];
			lbAdd [_zombzText, "" 	anything they want. With our custom features, we have taken epoch to  ""];
			lbAdd [_zombzText, "" 	a whole new level. Especially with our banking system that allows ""];
			lbAdd [_zombzText, "" 	players to  move their gold between different servers/maps when they  ""];
			lbAdd [_zombzText, "" 	get bored of the current map they play.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" - Coming soon, Epoch Cherno""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Panthera #1 192.223.27.54:2302 ""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 90 Minute Restart, starting at 00:00 GMT/EST""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Standalone Server""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" - Yes thats right, we do run a very popular standlone dayz server. ""];
			lbAdd [_zombzText, "" 	Unfortuantly we cannot modify it until the dayz dev team give us  ""];
			lbAdd [_zombzText, "" 	the go ahead. Still great fun to play!""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Standalone #1 66.55.154.89:2302""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" 120 Minute Restart, ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Minecraft""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" - We do also run a minecraft server. However work has not commenced on ""];
			lbAdd [_zombzText, "" 	this yet. So it is still a vanilla server. with a huge player slot. ""];
			lbAdd [_zombzText, "" 	Work will commence on this over the next few months.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ZombZ Minecraft 192.223.27.54""];
			lbAdd [_zombzText, "" Dayly Restart EST""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];


			
		};
		case ""FAQ"":
		{
			lbAdd [_zombzText, ""Common Questions and Answers""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" This rabbit is stalking me, what do I do?""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" Shoot it.""];
			lbAdd [_zombzText, "" This guy killed me from 10,000 meteres, hacks?""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" No this is not a hack, this is the last player to hit you.""];
			lbAdd [_zombzText, "" Im stuck unconsious. What do i do?""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" Relog, and read the known bugs section. Last resort, contact staff""];
			lbAdd [_zombzText, "" I am stuck in the ocean, Help!""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" Either swim, or contact a staff member via Teamspeak""];
			lbAdd [_zombzText, "" I have a suggestion""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" Please post these on our forums and they will be assesed.""];
			lbAdd [_zombzText, "" How do i hide the debug?""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" Simply hit F5""];
			lbAdd [_zombzText, "" I want a loadout/base or clanskin""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" You can get more information here, or visit our website to buy""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
		};
		case ""report"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""Report a hacker/bug""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Reporting Hackers/Glitchers/Rule Breakers""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" -	 So the problem we have is, arma 2 is a very poor engine sometimes.""];
			lbAdd [_zombzText, "" 	 Most of the hacker reports we receive can be put down to bad ""];
			lbAdd [_zombzText, "" 	 judgement blind luck, or lag/desync. Our custom built anti hack,""];
			lbAdd [_zombzText, "" 	 actually catches most hackers before we can even react. That said, ""];
			lbAdd [_zombzText, "" 	 Hacks can be sophisticated and while we run the best anti hack  ""];
			lbAdd [_zombzText, "" 	 going, we will never be able to 100% guarentee the safety  ""];
			lbAdd [_zombzText, "" 	 of the server.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" -  If you still want to report it, contact an admin in teamspeak or make ""];
			lbAdd [_zombzText, "" 	 a post on our forums. We do require some form of evidence and ""];
			lbAdd [_zombzText, "" 	 cannot just take a players word on the matter, Video is ""];
			lbAdd [_zombzText, "" 	 the strongest evidence, while screenshots are also helpful""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Reporting A Bug""];
			lbsetcolor[114, (lbsize 114)-1,[1,0,0,0.8]];
			lbAdd [_zombzText, "" -	 Before reporting a bug, please check the known bugs section.  ""];
			lbAdd [_zombzText, "" 	 Alot of the bugs in arma 2 can not be fixed by us. They require ""];
			lbAdd [_zombzText, "" 	 fixes from  further up the chain. People such as Bohemia. However. ""];
			lbAdd [_zombzText, "" 	 We do our best to find ways around any bugs that we come across. ""];
			lbAdd [_zombzText, ""	 So please visit our forums and let us know.""];
			lbAdd [_zombzText, """"];
		};
		case ""purchase"":
		{
			lbAdd [_zombzText, """"];
			lbAdd [_zombzText, ""Support our servers""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" There are many different ways you can support our servers. Wether you""];
			lbAdd [_zombzText, "" support us financially, by buying ingame perks (such as bases/loadouts)""];
			lbAdd [_zombzText, "" or by becoming part of our staff team, and helping out with keeping""];
			lbAdd [_zombzText, "" players happy.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" If you are interested in becoming staff, please visit our forums or""];
			lbAdd [_zombzText, "" have a chat with management on our teamspeak.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" If you would like to support us financially and receive in game perks""];
			lbAdd [_zombzText, "" for it, then please feel free to visit our website or read the sections""];
			lbAdd [_zombzText, "" below for more information.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Thank you for supporting ZombZ Servers. It is appreciated.""];

		};
		case ""about"":
		{
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""About Us""];
			lbAdd [_zombzText, "" ==================================================================""];
			lbAdd [_zombzText, "" Here at ZombZ Community. We aim""];
			lbAdd [_zombzText, "" to bring our players the best and""];
			lbAdd [_zombzText, "" most unique gameplay. We do this""];
			lbAdd [_zombzText, "" by introducing new features all""];
			lbAdd [_zombzText, "" the time. Written and improved""];
			lbAdd [_zombzText, "" by our own coders.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" Our aim at ZombZ is to become a""];
			lbAdd [_zombzText, "" massive community across all""];
			lbAdd [_zombzText, "" populuar mods. Bringing our unique""];
			lbAdd [_zombzText, "" features and experience to these""];
			lbAdd [_zombzText, "" servers. We also want to make a""];
			lbAdd [_zombzText, "" variety of game modes. From""];
			lbAdd [_zombzText, "" Hardcore mode to deathmatch style,""];
			lbAdd [_zombzText, "" and even event-only servers.""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""As one of the largest DayZ communities, ""];
			lbAdd [_zombzText, ""ZombZ has a very active forums page, ""];
			lbAdd [_zombzText, ""twitter, youtube, and facebook.""];
			lbAdd [_zombzText, ""These accounts are very active and responsive!""];
			lbAdd [_zombzText, ""So if you have a question, suggestion, ""];
			lbAdd [_zombzText, ""or if you simply want to get involved""];
			lbAdd [_zombzText, ""then don't hesitate to contact us!""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, ""	Twitter.com/ZombZnet""];
			lbAdd [_zombzText, ""	YouTube.com/user/ZombZCommunity""];
			lbAdd [_zombzText, ""	or just search for ZombZ on facebook!""];
			lbAdd [_zombzText, "" ""];
			lbAdd [_zombzText, "" www.ZombZ.net""];
			lbAdd [_zombzText, ""   ""];
			lbAdd [_zombzText, ""   ""];
		};
	};
};

if (p2SpT) then { _time = diag_tickTime; diag_log format ['menu showText.sqf finished, Time: %1',_time]; };

");

["ZombZ menu showText.sqf",_rExec] call fnc_p2_RemoteExecute;