@echo off

echo Making sure the server is shut down...

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe"  controlvm HeadlessTest acpipowerbutton


echo ...
echo Waiting 1 minute before powering up...
timeout 60
echo ...
echo Powering up Headless Client PC....
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe"  startvm HeadlessTest
timeout 10